<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" type="text/css" href="/zf-api-first/css/bootstrap.min.css" />
        <link rel="stylesheet" type="text/css" href="/zf-api-first/css/main.css" />
    </head>


    <body class="zfa1-home">
        <header class="navbar navbar-inverse navbar-fixed-top zfa1-nav" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <a href="./" class="navbar-brand">
                        <img src="/zf-api-first/img/zfa1-logo.png">
                    </a>
                </div>
            </div>
        </header>

        <main class="zfa1-masthead" id="content" role="main">
            <div class="container">
<!--                <img src="zfa1-hero.png" class="pull-right"> -->
                <h1>Apigility</h1>
                <p class="lead">
                    Apigility is a fully baked ZF2 application skeleton and set of modules that assist in the task of
                    creating API's. Whether you know a little or a lot about building useful, easy to consume, and well
                    structured API's your consumers, applications or mobile devices can immediately start interacting with.
                </p>

                <?php if (!class_exists('ZF\ApiFirstAdmin\Module', false)): ?>
                <p>
                    It is important you have your application in development mode.  The easiest way to
                    accomplish this is by copying <pre>config/development.config.php.dist</pre> to
                    <pre>config/development.config.php</pre> This file is in the .gitignore, so when
                    you're ready to move this app to production, the administration features will not
                    be available on the production server.  Once you have done this, you will see a
                    button below to take you to the admin section for API 1st development
                </p>
                <?php endif; ?>

                <p class="zfa-masthead-buttons">
                    <a href="/apidoc" class="btn btn-outline btn-lg">Live API Docs</a>
                    <?php if (class_exists('ZF\ApiFirstAdmin\Module', false)): ?>
                    <a href="/admin" class="btn btn-outline btn-lg">API Admin</a>
                    <?php endif; ?>
                </p>
            </div>
        </main>
    </body>
</html>
