<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('/zf-apigility/css/bootstrap.min.css') ?>" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('/zf-apigility-welcome/css/main.css') ?>" />
    </head>


    <body class="ag-welcome-home">
        <header class="navbar navbar-inverse navbar-fixed-top ag-welcome-nav" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <a href="<?php echo $this->url('zf-apigility/welcome') ?>" class="ag-welcome-navbar-brand">
<!--                        <img src="<?php echo $this->basePath('/zf-apigility/img/ag-logo.png') ?>">-->
                    </a>
                </div>
            </div>
        </header>

        <main class="ag-welcome-masthead" id="content" role="main">
            <div class="container">

                <img src="<?php echo $this->basePath('/zf-apigility-welcome/img/ag-hero.png') ?>">
                <p class="lead">
                    Apigility is an API Builder, designed to simplify creating
                    and maintaining useful, easy to consume, and well-structured APIs.
                </p>

                <?php if (!class_exists('ZF\Apigility\Admin\Module', false)): ?>
                <p>
                    It is important you have your application in development mode.  The easiest way to
                    accomplish this is by running:
                </p>

                <pre>
php public/index.php development enable
                </pre>

                <p>
                    This will copy <code>config/development.config.php.dist</code> to
                    <code>config/development.config.php</code> This file is in the .gitignore, so when
                    you're ready to move this app to production, the administration features will not
                    be available on the production server.  Once you have done this, you will see a
                    button below to take you to the admin section for API 1st development
                </p>
                <?php endif; ?>

                <p class="ag-masthead-buttons">
                    <?php if (class_exists('ZF\Apigility\Admin\Module', false)): ?>
                    <a href="<?php echo $this->url('zf-apigility/ui') ?>" class="btn btn-lg ag-welcome-btn-outline">Get Started!</a>
                    <?php endif; ?>
                </p>
            </div>
        </main>
    </body>
</html>
